"""Initial tables

Revision ID: 0001
Revises:
Create Date: 2025-01-01 12:00:00.000000

"""
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "0001"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table("hh_tokens",
                    sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
                    sa.Column("access_token", sa.String(length=255), nullable=False),
                    sa.Column("refresh_token", sa.String(length=255), nullable=False),
                    sa.Column("expires_in", sa.Integer(), nullable=False),
                    sa.Column("obtained_at", sa.DateTime(), nullable=False),
                    sa.PrimaryKeyConstraint("id")
                    )

    op.create_table("users",
                    sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
                    sa.Column("username", sa.String(length=50), nullable=False),
                    sa.Column("email", sa.String(length=100), nullable=False),
                    sa.Column("hashed_password", sa.String(length=255), nullable=False),
                    sa.Column("is_active", sa.Boolean(), nullable=False),
                    sa.Column("is_superuser", sa.Boolean(), nullable=False),
                    sa.Column("created_at", sa.DateTime(), nullable=False),
                    sa.PrimaryKeyConstraint("id")
                    )
    op.create_index(op.f("ix_users_email"), "users", ["email"], unique=True)
    op.create_index(op.f("ix_users_username"), "users", ["username"], unique=True)

    op.create_table("application_history",
                    sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
                    sa.Column("vacancy_id", sa.String(length=255), nullable=False),
                    sa.Column("resume_id", sa.String(length=255), nullable=False),
                    sa.Column("user_id", sa.String(length=255), nullable=True),
                    sa.Column("applied_at", sa.DateTime(), nullable=False),
                    sa.Column("hh_response", sa.JSON(), nullable=True),
                    sa.Column("status", sa.String(length=50), nullable=False),
                    sa.PrimaryKeyConstraint("id")
                    )
    op.create_index(op.f("ix_application_history_applied_at"), "application_history", ["applied_at"], unique=False)
    op.create_index(op.f("ix_application_history_resume_id"), "application_history", ["resume_id"], unique=False)
    op.create_index(op.f("ix_application_history_user_id"), "application_history", ["user_id"], unique=False)
    op.create_index(op.f("ix_application_history_vacancy_id"), "application_history", ["vacancy_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_application_history_vacancy_id"), table_name="application_history")
    op.drop_index(op.f("ix_application_history_user_id"), table_name="application_history")
    op.drop_index(op.f("ix_application_history_resume_id"), table_name="application_history")
    op.drop_index(op.f("ix_application_history_applied_at"), table_name="application_history")
    op.drop_table("application_history")
    op.drop_index(op.f("ix_users_username"), table_name="users")
    op.drop_index(op.f("ix_users_email"), table_name="users")
    op.drop_table("users")
    op.drop_table("hh_tokens")
    # ### end Alembic commands ###
